### ISSUE TITLE
A JavaScript error occurred in the main process (Different from # 93)

### ISSUE THREAD

**Issue by hkkhuang** [ethereum/remix-desktop#103]
Uncaught Exception:
TypeError: Cannot read property 'setWebSocket' of null
at /Applications/Remix IDE.app/Contents/Resources/app/main.js:153:14
at Server.<anonymous> (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@remix-project/remixd/src/websocket.js:28:17)
at Server.emit (events.js:205:15)
at emitErrorNT (net.js:1253:8)
at processTicksAndRejections (internal/process/task_queues.js:84:9)

![image](https://user-images.githubusercontent.com/21212031/147662373-33b321fa-4905-4963-98c6-b8a261001c39.png)

**Comment by ShockYoungCHN** [comment]
Same problem,
![image](https://user-images.githubusercontent.com/89326662/150945425-662a7ae7-7378-44a4-ac69-f3f61ab1a6c9.png)

**Comment by MauriceOne1** [comment]
same error

**macOS Monterey 12.1 (21C52)**

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at macosRelease (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/macos-release/index.js:26:26)
at osName (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/os-name/index.js:21:18)
at getUserAgent (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/universal-user-agent/dist-node/index.js:11:53)
at parseOptions (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@octokit/rest/lib/parse-client-options.js:80:57)
at new Octokit (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@octokit/rest/lib/constructor.js:23:31)
at new DeprecatedOctokit (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/@octokit/rest/index.js:29:10)
at new Github (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/electron-app-manager/dist/updater/repositories/Github.js:33:27)
at Object.exports.getRepository (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/electron-app-manager/dist/updater/repositories/index.js:12:16)
at new AppManager (/Applications/Remix IDE.app/Contents/Resources/app/node_modules/electron-app-manager/dist/updater/AppManager.js:49:38)
at Object.<anonymous> (/Applications/Remix IDE.app/Contents/Resources/app/main.js:39:17)
```

**Comment by Ayobami-Oloyade** [comment]
Please , I have the issue and I've not found a way out.

**Comment by QQ2287991080** [comment]
I have the same issue😥

**Comment by vagman** [comment]
Mac OS Monterey v. 12.5
RemixIDE v.0.21.1
Same problem here while trying to update.

**Comment by Jenil133** [comment]
can I get the solution of it, I have the same issue.

**Comment by Marvinmw** [comment]
hi, I am encountering the same issue. I use the latest version, and my MAC OS is macOS Ventura 13

**Comment by ChoyV** [comment]
Same

> hi, I am encountering the same issue. I use the latest version, and my MAC OS is macOS Ventura 13

**Comment by tsenovilla** [comment]
Same issue here.

> hi, I am encountering the same issue. I use the latest version, and my MAC OS is macOS Ventura 13

**Comment by unguest** [comment]
Hi !

Experimenting the same error here on Mac OS Ventura with both Universal & Intel version.

**Comment by tuanhv-0694** [comment]
Same in Ventura

**Comment by qdriven** [comment]
Same Issue in Ventura 13.0.1
