### ISSUE TITLE
Error on remix desktop v1.3.0 - Compiled and published whit bad imports 

### ISSUE THREAD

**Issue by RamaDL** [ethereum/remix-desktop#69]
Source code of remix desktop v1.3.0 is using import instead of require, this is causing remix error on open. The master branch it's ok and the published app is not.

Uncaught Exception:
/Applications/Remix IDE.app/Contents/Resources/app/main.js:1
import * as fs from 'fs-extra'
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Object.<anonymous> (/Applications/Remix IDE.app/Contents/Resources/electron.asar/browser/init.js:181:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)

**Comment by yann300** [comment]
sorry for the very late answer, how did you install remix?
