### ISSUE TITLE
Not able to save transactions as scenario [MacOS - Apple]

### ISSUE THREAD

**Issue by Tomas2D** [ethereum/remix-desktop#84]
Hello, I am not able to save transactions as a scenario. This bug is probably due to the fact that Remix tries to save under `/` aka root directory, which does not have permission to

<img width="542" alt="Snímek obrazovky 2021-10-30 v 14 07 30" src="https://user-images.githubusercontent.com/15633909/139532271-331c9c1e-5a8a-4dfb-973f-61137fa1d200.png">. 

No error message is displayed when I try to run Remix IDE Online and then make a connection to the local file system with `remixd` I am not able to do that export as well. The only difference is that I can see the error message in the console.

```
Error: Error: Cannot read/write to path outside shared folder.
    at RemixdClient.exists (/Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/services/remixdClient.js:79:19)
    at Object.<anonymous> (/Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/@remixproject/plugin/lib/connector.js:67:56)
    at Generator.next (<anonymous>)
    at /Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/tslib/tslib.js:110:16)
    at /Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/@remixproject/plugin/lib/connector.js:30:86
    at WebSocket.<anonymous> (/Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/@remixproject/plugin-ws/lib/ws.js:35:17)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/Users/Tomas2D/.nvm/versions/node/v12.16.3/lib/node_modules/@remix-project/remixd/node_modules/ws/lib/websocket.js:983:20)
```

Thanks

**Comment by Tomas2D** [comment]
Nope, it was normally opened from /Applications folder via Finder.

**Comment by sudo-monkey** [comment]
same here. the appimage already granted read / write access
![image](https://user-images.githubusercontent.com/83343556/215328527-d6dad545-57dc-4b76-9bf4-d6a4f9668707.png)
